name: delivery_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get:
  dio:
  flutter_easyloading:
  flutter_screenutil:
  logger:
  connectivity_plus: ^4.0.2
  url_launcher:
  shared_value:
  intl:
  any_image_view:
  easy_debounce:
  font_awesome_flutter:
  flutter_spinkit:
  skeletonizer: ^2.1.0+1
  dropdown_search:
  animations:
  pinput:
  timeline_tile:
  flutter_dotenv:
  easy_date_timeline: ^2.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  icons_launcher: ^3.0.2
  android_notification_icons:

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/png/
    - assets/logo/

icons_launcher:
  image_path: "assets/logo/icon.png"
  platforms:
    android:
      enable: true
      image_path: "assets/logo/icon.png"
      notification_image: "assets/logo/icon.png"
      # adaptive_background_color: '#ffffff'
      adaptive_background_image: "assets/logo/icon.png"
      adaptive_foreground_image: "assets/logo/icon.png"
      adaptive_round_image: "assets/logo/icon.png"
      adaptive_monochrome_image: "assets/logo/icon.png"
    ios:
      enable: true
      image_path: "assets/logo/icon.png"
      dark_path: "assets/logo/icon.png"
      tinted_path: "assets/logo/icon.png"

android_notification_icons:
  image_path: 'assets/png/logo.png'
  icon_name: 'ic_notification'